### ISSUE TITLE
여기에 다트&플러터 질문 올리면 될까요?

### ISSUE THREAD

**Issue by digerati73** [MyStoryG/dart_flutter#1]
여기에 모바일 앱 개발을 위한 
다트&플러터 질문 올리면 될까요? 디지털북스 카페나 홈페이지에서는 질답이 않되는 듯해서요

**Comment by digerati73** [comment]
안드로이드 스튜디오 에뮬레이터 실행에서 자꾸만  AVD Manager에서  the emulator process was killed가 뜨는데 폭폭하네요
어떻게 해야될지...

**Comment by MyStoryG** [comment]
확인이 늦어서 죄송합니다. 문제가 해결되셨을까요? 환경 설정 관련 문제는 에러 메시지만으로 도움을 드리기 어려운 점 양해 부탁드립니다.
